export const GET_WORKOUTS = 'GET_WORKOUTS';
export const CREATE_WORKOUT = 'CREATE_WORKOUT';
export const UPDATE_WORKOUT = 'UPDATE_WORKOUT';
export const DELETE_WORKOUT = 'DELETE_WORKOUT';
export const GET_EXERCISES = 'GET_EXERCISES';
export const CREATE_EXERCISE = 'CREATE_EXERCISE';
export const UPDATE_EXERCISE = 'UPDATE_EXERCISE';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';
